# @package model
name: llama32_1B_instruct
model_id: meta-llama/Llama-3.2-1B-Instruct
end_of_turn_token: <|eot_id|>
attn_implementation: sdpa
token_level_replacement: null
dtype: float32
ignore_first_n_tokens_per_sample_during_collection: 0 # This is for activation collection. 
ignore_first_n_tokens_per_sample_during_training: 2 # This is for any training ontop of the collected activations (and applies ontop of the ignore_first_n_tokens_per_sample_during_collection)

has_enable_thinking: false # The tokenizer has the enable_thinking parameter